import { Link, useLocation } from "react-router-dom";
import { AnimatePresence, motion } from "framer-motion";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { dashboardNavigation } from "@/constants/navigation";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { LogoMark } from "@/components/shell/brand";
interface SidebarProps { collapsed: boolean; mobileOpen: boolean; onToggle: () => void; onCloseMobile: () => void; }
export function Sidebar({ collapsed, mobileOpen, onToggle, onCloseMobile }: SidebarProps) {
  const location = useLocation();
  const isActive = (href: string, exact?: boolean) => exact ? location.pathname === href : location.pathname === href || location.pathname.startsWith(`${href}/`);
  const content = <div className="flex h-full flex-col"><div className={cn("flex h-16 items-center border-b px-4", collapsed ? "justify-center" : "justify-between")}><Link to="/dashboard" onClick={onCloseMobile} className="focus-ring flex items-center gap-2.5" aria-label="Go to dashboard"><LogoMark /><AnimatePresence initial={false}>{!collapsed && <motion.span initial={{ opacity: 0, width: 0 }} animate={{ opacity: 1, width: "auto" }} exit={{ opacity: 0, width: 0 }} className="overflow-hidden whitespace-nowrap text-sm font-semibold tracking-tight">VideoScene<span className="text-primary">RAG</span></motion.span>}</AnimatePresence></Link>{!collapsed && <Button variant="ghost" size="icon" onClick={onToggle} className="hidden h-8 w-8 lg:inline-flex" aria-label="Collapse sidebar"><ChevronLeft className="h-4 w-4" /></Button>}<Button variant="ghost" size="icon" onClick={onCloseMobile} className="ml-auto h-8 w-8 lg:hidden" aria-label="Close navigation"><X className="h-4 w-4" /></Button></div><nav aria-label="Dashboard navigation" className="flex-1 space-y-1 overflow-y-auto px-3 py-5">{dashboardNavigation.map(({ label, href, icon: Icon, exact }) => { const active = isActive(href, exact); return <Link key={href} to={href} onClick={onCloseMobile} aria-current={active ? "page" : undefined} title={collapsed ? label : undefined} className={cn("focus-ring group relative flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition duration-fast", collapsed && "justify-center px-2", active ? "bg-secondary font-semibold text-secondary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground")}>{active && <motion.span layoutId="sidebar-active" className="absolute bottom-1.5 left-0 top-1.5 w-0.5 rounded-full bg-primary" transition={{ duration: .2 }} /> }<Icon className={cn("h-4 w-4 shrink-0 transition-transform duration-fast group-hover:scale-105", active && "text-primary")} /><AnimatePresence initial={false}>{!collapsed && <motion.span initial={{ opacity: 0, width: 0 }} animate={{ opacity: 1, width: "auto" }} exit={{ opacity: 0, width: 0 }} className="overflow-hidden whitespace-nowrap">{label}</motion.span>}</AnimatePresence></Link>; })}</nav><div className={cn("border-t p-3", collapsed ? "flex justify-center" : "")}><Button variant="ghost" size={collapsed ? "icon" : "sm"} onClick={onToggle} className="hidden w-full lg:inline-flex" aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"}>{collapsed ? <ChevronRight className="h-4 w-4" /> : <span className="text-xs text-muted-foreground">Collapse menu</span>}</Button></div></div>;
  return <><motion.aside initial={false} animate={{ width: collapsed ? 76 : 256 }} transition={{ duration: .24, ease: [.2, .8, .2, 1] }} className="fixed inset-y-0 left-0 z-40 hidden border-r bg-card/90 backdrop-blur-xl lg:block">{content}</motion.aside><AnimatePresence>{mobileOpen && <><motion.button initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-40 bg-slate-950/40 lg:hidden" onClick={onCloseMobile} aria-label="Close navigation overlay" /><motion.aside role="dialog" aria-modal="true" aria-label="Mobile navigation" initial={{ x: "-100%" }} animate={{ x: 0 }} exit={{ x: "-100%" }} transition={{ duration: .24, ease: [.2, .8, .2, 1] }} className="fixed inset-y-0 left-0 z-50 w-[min(19rem,85vw)] bg-card shadow-elevated lg:hidden">{content}</motion.aside></>}</AnimatePresence></>;
}
