import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { motion, useInView } from "framer-motion";
import { ArrowRight, BrainCircuit, Check, ChevronDown, CircleDot, FileSearch, Github, Globe2, Layers3, Menu, MessageSquareText, Mic2, Network, Play, ScanText, Search, ShieldCheck, Sparkles, Video, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { staggerContainer, slideUp, scaleIn } from "@/animations/motion";

const features = [
  { icon: Layers3, title: "Scene detection", text: "Find the visual chapters and transitions that give every recording its shape.", tone: "indigo" },
  { icon: ScanText, title: "OCR intelligence", text: "Recover slide text, labels, and on-screen details with temporal context.", tone: "cyan" },
  { icon: Mic2, title: "Speech recognition", text: "Turn spoken explanations into timestamped, speaker-aware evidence.", tone: "violet" },
  { icon: Search, title: "Semantic search", text: "Ask naturally, even when your memory does not match the exact words.", tone: "indigo" },
  { icon: FileSearch, title: "Evidence retrieval", text: "Get an answer with the source interval, confidence, and citations attached.", tone: "cyan" },
  { icon: MessageSquareText, title: "AI chat", text: "Explore a video through follow-up questions that stay grounded in the source.", tone: "violet" },
  { icon: Video, title: "Timeline navigation", text: "Move from a claim to the precise frame, transcript, or topic that supports it.", tone: "indigo" },
  { icon: Network, title: "Knowledge graph", text: "See concepts, events, and relationships as a connected memory of the video.", tone: "cyan" },
];
const workflow = [
  ["01", "Upload", "Give the system a video, lecture, meeting, or investigation.", Video],
  ["02", "Process", "Speech, scenes, frames, OCR, and structure become evidence.", BrainCircuit],
  ["03", "Search", "Ask the question the way you remember it—not the way it was said.", Search],
  ["04", "Retrieve", "Return to the exact moment with confidence and citations.", FileSearch],
] as const;
const benefits = [
  ["Legal teams", "Review depositions, hearings, and recorded interviews with a verifiable trail back to the source."],
  ["Investigators", "Surface the moment, person, object, or visual detail that matters across long recordings."],
  ["Researchers", "Move from a half-remembered concept to the precise explanation, diagram, or quote."],
  ["Enterprises", "Make internal knowledge searchable without asking people to rewatch every meeting."],
];
const bars = ["h-10", "h-16", "h-7", "h-20", "h-12", "h-24", "h-14", "h-10", "h-28", "h-16", "h-20", "h-12", "h-24", "h-9", "h-16", "h-11", "h-28", "h-14", "h-20", "h-8", "h-16", "h-10", "h-24", "h-14"];

function Reveal({ children, className, delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });
  return <motion.div ref={ref} variants={slideUp} initial="hidden" animate={inView ? "visible" : "hidden"} transition={{ delay }} className={className}>{children}</motion.div>;
}
function Logo() { return <Link to="/" aria-label="VideoSceneRAG home" className="focus-ring flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-white shadow-lg shadow-indigo-200 dark:bg-white dark:text-slate-950"><BrainCircuit className="h-5 w-5" /></span><span className="font-semibold tracking-tight">VideoScene<span className="text-primary">RAG</span></span></Link>; }
function SectionLabel({ children }: { children: React.ReactNode }) { return <div className="mb-5 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-primary"><span className="h-1.5 w-1.5 rounded-full bg-current" />{children}</div>; }

export function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  return <div className="overflow-hidden bg-background text-foreground">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/60 bg-background/75 backdrop-blur-2xl dark:border-slate-800/60" aria-label="Main navigation">
      <div className="mx-auto flex h-[4.5rem] max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><div className="hidden items-center gap-7 lg:flex"><a href="#features" className="focus-ring text-sm text-muted-foreground hover:text-foreground">Features</a><a href="#workflow" className="focus-ring text-sm text-muted-foreground hover:text-foreground">Workflow</a><a href="#documentation" className="focus-ring text-sm text-muted-foreground hover:text-foreground">Documentation</a><a href="#pricing" className="focus-ring text-sm text-muted-foreground hover:text-foreground">Pricing</a></div><div className="hidden items-center gap-2 sm:flex"><Button variant="ghost" size="sm" asChild><Link to="/login">Log in</Link></Button><Button size="sm" asChild><Link to="/videos/new">Get started <ArrowRight className="h-3.5 w-3.5" /></Link></Button></div><Button variant="ghost" size="icon" className="sm:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Close menu" : "Open menu"}>{menuOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</Button></div>
      {menuOpen && <div className="border-t border-border bg-background px-5 py-4 sm:hidden"><div className="flex flex-col gap-1"><a onClick={closeMenu} href="#features" className="rounded-lg px-3 py-3 text-sm text-muted-foreground">Features</a><a onClick={closeMenu} href="#workflow" className="rounded-lg px-3 py-3 text-sm text-muted-foreground">Workflow</a><a onClick={closeMenu} href="#documentation" className="rounded-lg px-3 py-3 text-sm text-muted-foreground">Documentation</a><a onClick={closeMenu} href="#pricing" className="rounded-lg px-3 py-3 text-sm text-muted-foreground">Pricing</a><div className="mt-2 flex gap-2 border-t pt-3"><Button variant="outline" className="flex-1" asChild><Link to="/login">Log in</Link></Button><Button className="flex-1" asChild><Link to="/videos/new">Get started</Link></Button></div></div></div>}
    </nav>

    <main>
      <section className="relative isolate px-5 pb-24 pt-36 lg:px-8 lg:pb-32 lg:pt-48"><div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden"><div className="absolute left-1/2 top-[-20rem] h-[45rem] w-[45rem] -translate-x-1/2 rounded-full bg-indigo-300/20 blur-3xl dark:bg-indigo-700/20" /><div className="absolute right-[-12rem] top-36 h-[28rem] w-[28rem] rounded-full bg-cyan-200/20 blur-3xl dark:bg-cyan-900/20" /><div className="absolute inset-0 bg-[linear-gradient(to_right,hsl(var(--border)/.18)_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border)/.18)_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:linear-gradient(to_bottom,white,transparent_80%)]" /></div><div className="mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[.92fr_1.08fr] lg:gap-12"><motion.div variants={staggerContainer} initial="hidden" animate="visible"><motion.div variants={slideUp}><Badge variant="secondary" className="gap-2 px-3 py-1.5"><Sparkles className="h-3.5 w-3.5 text-primary" /> The memory layer for video</Badge></motion.div><motion.h1 variants={slideUp} className="mt-7 max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.065em] sm:text-6xl lg:text-[5.4rem]">Understand every<br /><span className="bg-gradient-to-r from-indigo-600 via-violet-600 to-cyan-500 bg-clip-text text-transparent">moment that matters.</span></motion.h1><motion.p variants={slideUp} className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground sm:text-xl">VideoSceneRAG turns long-form video into a searchable, explainable memory—so you can ask a question and go straight to the evidence.</motion.p><motion.div variants={slideUp} className="mt-9 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/videos/new">Get started <ArrowRight className="h-4 w-4" /></Link></Button><Button size="lg" variant="outline" onClick={() => document.getElementById("workflow")?.scrollIntoView({ behavior: "smooth" })}><Play className="h-4 w-4" /> View demo</Button></motion.div><motion.div variants={slideUp} className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-3 text-xs text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-500" /> Evidence-first by design</span><span className="flex items-center gap-2"><Zap className="h-4 w-4 text-amber-500" /> Built for long-form video</span></motion.div></motion.div><HeroIllustration /></div></section>

      <section id="value" className="border-y border-border/70 bg-card/35 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><Reveal className="mx-auto max-w-2xl text-center"><SectionLabel>One source of truth</SectionLabel><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-5xl">From a video file to a living memory.</h2><p className="mt-5 text-base leading-7 text-muted-foreground sm:text-lg">Every layer of understanding stays connected to the original timeline. No black box summaries. No lost context.</p></Reveal><motion.div variants={staggerContainer} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }} className="mt-14 grid gap-3 md:grid-cols-5">{[["Upload", "your source", Video], ["Process", "every signal", BrainCircuit], ["Search", "by meaning", Search], ["Ask", "in plain language", MessageSquareText], ["Retrieve", "the evidence", FileSearch]].map(([title, text, Icon], i) => <motion.div variants={scaleIn} key={title as string} className="relative"><Card className="h-full border-border/70 bg-background/65 p-5 transition duration-normal hover:-translate-y-1 hover:shadow-elevated"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-secondary text-primary"><Icon className="h-5 w-5" /></span><span className="font-mono text-xs text-muted-foreground">0{i + 1}</span></div><h3 className="mt-5 font-semibold">{title as string}</h3><p className="mt-1 text-sm text-muted-foreground">{text as string}</p></Card>{i < 4 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-5 w-5 -translate-y-1/2 rounded-full bg-background text-muted-foreground md:block" />}</motion.div>)}</motion.div></div></section>

      <section id="features" className="px-5 py-20 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><Reveal><SectionLabel>Built for understanding</SectionLabel><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="max-w-2xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">The details are the product.</h2><p className="max-w-md text-base leading-7 text-muted-foreground">VideoSceneRAG brings the modalities that matter together, then makes each answer auditable.</p></div></Reveal><motion.div variants={staggerContainer} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }} className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{features.map(({ icon: Icon, title, text, tone }) => <motion.div variants={slideUp} key={title}><Card className="group h-full border-border/70 p-6 transition duration-normal hover:-translate-y-1 hover:border-primary/30 hover:shadow-elevated"><div className={cn("grid h-11 w-11 place-items-center rounded-xl", tone === "cyan" ? "bg-cyan-50 text-cyan-600 dark:bg-cyan-950/50" : tone === "violet" ? "bg-violet-50 text-violet-600 dark:bg-violet-950/50" : "bg-indigo-50 text-indigo-600 dark:bg-indigo-950/50")}><Icon className="h-5 w-5 transition duration-normal group-hover:scale-110" /></div><h3 className="mt-6 font-semibold tracking-tight">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><ArrowRight className="mt-6 h-4 w-4 text-muted-foreground transition duration-normal group-hover:translate-x-1 group-hover:text-primary" /></Card></motion.div>)}</motion.div></div></section>

      <section id="workflow" className="relative overflow-hidden bg-slate-950 px-5 py-20 text-white lg:px-8 lg:py-32"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(99,102,241,.28),transparent_45%)]" /><div className="relative mx-auto max-w-7xl"><Reveal><SectionLabel>Under the hood</SectionLabel><h2 className="max-w-2xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">A pipeline that keeps the source in view.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-400">The system builds a hierarchy from raw signal to verified answer, with the timeline as the common coordinate system.</p></Reveal><motion.div variants={staggerContainer} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }} className="relative mt-16 grid gap-8 md:grid-cols-4 md:gap-0">{workflow.map(([number, title, text, Icon], index) => <motion.div variants={slideUp} key={title} className="relative md:px-5 first:md:pl-0 last:md:pr-0"><div className="hidden h-px w-full bg-gradient-to-r from-indigo-500/70 to-cyan-400/40 md:absolute md:left-1/2 md:top-6 md:block" /><div className="relative"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/10 text-cyan-200"><Icon className="h-5 w-5" /></span><span className="font-mono text-xs text-slate-500">{number}</span></div><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-2 max-w-[15rem] text-sm leading-6 text-slate-400">{text}</p></div></motion.div>)}</motion.div></div></section>

      <section className="px-5 py-20 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid items-center gap-14 lg:grid-cols-[.8fr_1.2fr]"><Reveal><SectionLabel>For the moments that matter</SectionLabel><h2 className="max-w-xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Less rewatching.<br /><span className="text-muted-foreground">More knowing.</span></h2><p className="mt-6 max-w-lg text-base leading-7 text-muted-foreground">Whether your archive is a case file, a research library, or a company’s collective memory, the fastest path to clarity is a trustworthy path back to the source.</p><Button variant="outline" className="mt-8" asChild><Link to="/videos/new">Explore the workspace <ArrowRight className="h-4 w-4" /></Link></Button></Reveal><motion.div variants={staggerContainer} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }} className="grid gap-3 sm:grid-cols-2">{benefits.map(([title, text]) => <motion.div variants={slideUp} key={title} className="surface rounded-2xl p-6"><div className="flex items-center justify-between"><h3 className="font-semibold">{title}</h3><Check className="h-4 w-4 text-emerald-500" /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></motion.div>)}</motion.div></div></div></section>

      <section id="documentation" className="px-5 pb-20 lg:px-8 lg:pb-32"><div className="mx-auto max-w-7xl"><Reveal><div className="gradient-soft relative overflow-hidden rounded-3xl border border-indigo-100 p-8 dark:border-indigo-900/60 sm:p-12"><div className="relative z-10 max-w-2xl"><SectionLabel>See it in context</SectionLabel><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Your video has more to say.</h2><p className="mt-5 max-w-xl text-base leading-7 text-muted-foreground">The best answers are not just fluent. They are anchored, inspectable, and easy to share with the people who need to trust them.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild><Link to="/videos/new">Start with a video <ArrowRight className="h-4 w-4" /></Link></Button><Button variant="outline" asChild><a href="#footer">Read the docs <ChevronDown className="h-4 w-4" /></a></Button></div></div><div className="absolute -right-8 -top-16 hidden h-80 w-80 rounded-full border border-indigo-200/60 sm:block dark:border-indigo-700/40"><div className="absolute inset-10 rounded-full border border-cyan-200/60 dark:border-cyan-700/40"><div className="absolute inset-10 rounded-full border border-violet-200/60 dark:border-violet-700/40" /></div></div></div></Reveal></div></section>

      <section id="pricing" className="border-t border-border/70 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><Reveal className="mx-auto max-w-2xl text-center"><SectionLabel>Trusted by what comes next</SectionLabel><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-5xl">A clearer way to work with video.</h2><p className="mt-5 text-muted-foreground">Teams are building a more searchable, more accountable memory—one recording at a time.</p></Reveal><motion.div variants={staggerContainer} initial="hidden" whileInView="visible" viewport={{ once: true }} className="mt-12 grid gap-3 md:grid-cols-3">{["“A powerful foundation for making visual knowledge as searchable as text.”", "“The confidence layer is what makes this useful for serious review.”", "“We finally have a way to ask the archive instead of browsing it.”"].map((quote, i) => <motion.div variants={slideUp} key={quote}><Card className="h-full border-border/70 p-6"><div className="flex gap-1 text-amber-400">{Array.from({ length: 5 }).map((_, index) => <CircleDot key={index} className="h-3 w-3 fill-current" />)}</div><p className="mt-5 text-sm leading-6 text-muted-foreground">{quote}</p><div className="mt-6 flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-full bg-secondary text-primary"><Globe2 className="h-4 w-4" /></div><div><p className="text-xs font-semibold">Future customer</p><p className="text-[11px] text-muted-foreground">Testimonial placeholder {i + 1}</p></div></div></Card></motion.div>)}</motion.div></div></section>
    </main>
    <footer id="footer" className="border-t border-border/70 bg-card/35 px-5 py-12 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-10 md:flex-row md:items-start md:justify-between"><div><Logo /><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">A searchable, explainable memory for every important video.</p></div><div className="grid grid-cols-2 gap-x-14 gap-y-8 text-sm sm:grid-cols-3"><div><p className="mb-3 font-semibold">Product</p><div className="space-y-2 text-muted-foreground"><a className="block hover:text-foreground" href="#features">Features</a><a className="block hover:text-foreground" href="#workflow">Workflow</a><a className="block hover:text-foreground" href="#pricing">Pricing</a></div></div><div><p className="mb-3 font-semibold">Resources</p><div className="space-y-2 text-muted-foreground"><a className="block hover:text-foreground" href="#documentation">Documentation</a><a className="block hover:text-foreground" href="#footer">Contact</a><a className="block hover:text-foreground" href="#footer">Status</a></div></div><div><p className="mb-3 font-semibold">Connect</p><div className="space-y-2 text-muted-foreground"><a className="flex items-center gap-2 hover:text-foreground" href="#footer"><Github className="h-3.5 w-3.5" /> GitHub</a><a className="flex items-center gap-2 hover:text-foreground" href="#footer"><Globe2 className="h-3.5 w-3.5" /> Community</a></div></div></div></div><div className="mx-auto mt-12 flex max-w-7xl flex-col justify-between gap-3 border-t border-border/70 pt-5 text-xs text-muted-foreground sm:flex-row"><span>© 2026 VideoSceneRAG. Built for evidence.</span><span>Privacy · Terms · Security</span></div></footer>
  </div>;
}

function HeroIllustration() {
  return (
    <motion.div variants={scaleIn} initial="hidden" animate="visible" className="relative mx-auto w-full max-w-2xl">
      <div className="absolute -inset-10 rounded-full bg-indigo-300/20 blur-3xl dark:bg-indigo-600/15" />
      <div className="relative rounded-[2rem] border border-slate-200/80 bg-white/60 p-3 shadow-elevated backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/60">
        <div className="overflow-hidden rounded-[1.5rem] bg-slate-950 p-5 text-white sm:p-7">
          <div className="flex items-center justify-between text-[11px] text-slate-400">
            <span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400" /> semantic index ready</span>
            <span className="font-mono">VIDEO_001 / 42:18</span>
          </div>
          <div className="mt-7 grid grid-cols-[1.35fr_.65fr] gap-3">
            <div className="relative min-h-64 overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-indigo-950 via-slate-900 to-cyan-950 p-4">
              <div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(148,163,184,.16)_1px,transparent_1px),linear-gradient(90deg,rgba(148,163,184,.16)_1px,transparent_1px)] [background-size:2rem_2rem]" />
              <div className="relative flex h-full flex-col justify-between">
                <div className="flex items-start justify-between"><Badge className="border-white/10 bg-white/10 text-cyan-200">Scene 07</Badge><span className="rounded bg-rose-400/20 px-2 py-1 text-[9px] text-rose-200"><ScanText className="mr-1 inline h-3 w-3" /> OCR</span></div>
                <div className="relative mx-auto grid h-32 w-44 place-items-center"><div className="absolute h-24 w-24 rounded-full border border-cyan-300/40 shadow-[0_0_45px_rgba(103,232,249,.35)]" /><div className="absolute h-12 w-12 rounded-full bg-cyan-300/20 ring-1 ring-cyan-200/70" /><Network className="relative h-8 w-8 text-cyan-200" /><span className="absolute left-0 top-4 h-2 w-2 rounded-full bg-violet-300 shadow-[0_0_12px_rgba(196,181,253,.9)]" /><span className="absolute right-2 top-8 h-2 w-2 rounded-full bg-indigo-300 shadow-[0_0_12px_rgba(165,180,252,.9)]" /><span className="absolute bottom-2 left-12 h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_12px_rgba(103,232,249,.9)]" /></div>
                <div className="rounded-lg border border-white/10 bg-white/5 p-2 font-mono text-[9px] leading-4 text-slate-300">context → server → tools<br /><span className="text-cyan-300">semantic relation detected</span></div>
              </div>
            </div>
            <div className="flex flex-col gap-3">
              <div className="rounded-2xl border border-white/10 bg-white/[.06] p-3"><div className="flex items-center gap-2 text-[10px] font-semibold text-violet-200"><MessageSquareText className="h-3.5 w-3.5" /> transcript</div><p className="mt-3 text-[11px] leading-5 text-slate-300">“The key distinction is how context is carried…”</p><span className="mt-2 block font-mono text-[9px] text-slate-500">12:48.320</span></div>
              <div className="flex-1 rounded-2xl border border-white/10 bg-white/[.06] p-3"><div className="flex items-center gap-2 text-[10px] font-semibold text-cyan-200"><FileSearch className="h-3.5 w-3.5" /> citation S1</div><div className="mt-3 flex items-center gap-2"><span className="h-px flex-1 bg-cyan-300/60" /><ArrowRight className="h-3 w-3 text-cyan-300" /><span className="h-px w-5 bg-cyan-300/60" /></div><p className="mt-3 text-[10px] leading-4 text-slate-400">Verified evidence anchor</p><Badge variant="success" className="mt-3 text-[9px]">96% quality</Badge></div>
            </div>
          </div>
          <div className="mt-4 rounded-xl border border-white/10 bg-white/[.04] p-3"><div className="flex items-center justify-between text-[9px] text-slate-500"><span>timeline evidence</span><span className="font-mono">00:00 — 42:18</span></div><div className="mt-3 flex h-9 items-end gap-1">{bars.map((height, index) => <span key={index} className={cn("flex-1 rounded-t-sm", height, index === 9 || index === 10 ? "bg-cyan-300" : "bg-indigo-400/50")} />)}</div><div className="mt-2 h-1 rounded-full bg-white/10"><div className="h-full w-[42%] rounded-full bg-gradient-to-r from-indigo-400 to-cyan-300" /></div></div>
        </div>
      </div>
      <div className="absolute -bottom-5 -left-3 hidden rounded-2xl border border-indigo-100 bg-white p-4 shadow-xl dark:border-slate-700 dark:bg-slate-900 sm:block"><div className="flex items-center gap-2 text-xs font-semibold"><span className="grid h-7 w-7 place-items-center rounded-lg bg-emerald-100 text-emerald-600"><Check className="h-4 w-4" /></span> Verified context</div><p className="mt-2 text-[10px] text-muted-foreground">1 primary · 3 supporting sources</p></div>
    </motion.div>
  );
}

